### PR TITLE
Code refresh and new features

### PR DESCRIPTION
**Pull request by dangreen**

### CODE REVIEW

**Comment by mohsen1** [comment]
Hi 
this is a fork. Can you make the change request to the main repo?

**Comment by dangreen** [comment]
@mohsen1 no signals from main repo owner

**Comment by dangreen** [comment]
@mohsen1 I don't want publish on npm "yet-another-service-worker-loader", I want upgrade this one.

**Comment by mohsen1** [comment]
@dangreen I completely forgot [I said](https://www.npmjs.com/package/service-worker-loader):

> A fork of serviceworker-loader that is actively maintained.

🤦‍♂️

**Comment by mohsen1** [comment]
Published at 1.0.0

Sorry for the delay

**Pull request merged**
