### PR TITLE
Webpack 4 compatibility cont.

### PR DESCRIPTION
**Pull request by odama626**
replace this.options with this.query for webpack 4.0, still falls back to this.options.

also found an incompatibility with webpack hot module replacement trying to access window inside of the service worker.  Maybe we should make note of that in the readme? https://github.com/webpack/webpack/issues/6642

Also found deprecation warnings for Tapable but I'm not sure what dependency was causing it.

I apologize for the half-baked PR earlier

Edit: I think this will fix the peer dependency issues with David as well

### CODE REVIEW

**Comment by dangreen** [comment]
@mohsen1 can you give me access rights to maintain this repo?

**Comment by mohsen1** [comment]
@dangreen you are a maintainer now https://github.com/mohsen1/service-worker-loader/invitations

**Comment by mohsen1** [comment]
I will make you an npm owner once you decided to publish

**Comment by dangreen** [comment]
@mohsen1 https://www.npmjs.com/~dangreen

**Comment by dangreen** [comment]
@mohsen1 can you transfer this repo to me, to full control? (https://github.com/TrigenSoftware)

**Comment by mohsen1** [comment]
I prefer to have it here for now.

**Comment by dangreen** [comment]
@moshen1 ok. Can you connect travis-ci and greenkeeper for this repo?

**Comment by dangreen** [comment]
@mohsen1 what about access to publish on npm? did you connect greenkeeper?

**Comment by mohsen1** [comment]
greenkeeper is acting weird and I couldn't connect to it. if you cut a release I can publish to npm.

**Comment by dangreen** [comment]
@mohsen1 https://github.com/mohsen1/service-worker-loader/releases/tag/v3.0.0
Please try connect greenkeeper again, it requires ci with tests - now we have it.

**Comment by mohsen1** [comment]
Thanks! it's published now. Greenkeeper is also enabled now.

**Pull request merged**
