### PR TITLE
Dependencies updates, fixes

### PR DESCRIPTION
**Pull request by dangreen**

### CODE REVIEW

**Comment by mohsen1** [comment]
@dangreen what is your npm user name? I will make you an owner to publish

**Comment by dangreen** [comment]
@mohsen1 [dangreen](https://www.npmjs.com/~dangreen)

What about [Dependabot](https://github.com/mohsen1/service-worker-loader/issues/12)?

**Comment by mohsen1** [comment]
@dangreen you're an owner now. Thank you for maintaining this!

**Comment by dangreen** [comment]
@mohsen1 thanks, also please enable dependabot for this repo 🙏

**Pull request merged**
